export const data = [
  {
    id: 1,
    title: "patiekalas#1",
    category: "breakfast",
    price: 15.99,
    img: "./images/example.webp",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "patiekalas#2",
    category: "lunch",
    price: 13.99,
    img: "./images/...",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "patiekalas#3",
    category: "dinner",
    price: 6.99,
    img: "./images/...",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "patiekalas#4",
    category: "drinks",
    price: 20.99,
    img: "./images/...",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "patiekalas#5",
    category: "deserts",
    price: 22.99,
    img: "./images/...",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "patiekalas#6",
    category: "breakfast",
    price: 18.99,
    img: "./images/...",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "patiekalas#7",
    category: "lunch",
    price: 8.99,
    img: "./images/...",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "patiekalas#8",
    category: "dinner",
    price: 12.99,
    img: "./images/...",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "patiekalas#9",
    category: "drinks",
    price: 16.99,
    img: "./images/...",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: "patiekalas#10",
    category: "deserts",
    price: 22.99,
    img: "./images/...",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 11,
    title: "patiekalas#11",
    category: "breakfast",
    price: 22.99,
    img: "./images/...",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 12,
    title: "patiekalas#12",
    category: "lunch",
    price: 22.99,
    img: "./images/...",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 13,
    title: "patiekalas#13",
    category: "dinner",
    price: 22.99,
    img: "./images/...",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 14,
    title: "patiekalas#14",
    category: "deserts",
    price: 22.99,
    img: "./images/...",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
